### ISSUE TITLE
App crash before starting!

### ISSUE THREAD

**Issue by Jacopx** [mooow/labyrinth#1]
Starting from the software just pulled (commit 7333225), when I try to run it I get:
```
$ python3 -m labyrinth
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jacopx/Development/labyrinth/labyrinth/__main__.py", line 52, in <module>
    curses.wrapper(main, configurator.conf, win1, win2)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/jacopx/Development/labyrinth/labyrinth/__main__.py", line 17, in main
    r1 = run(win1, s1, "DFS")
  File "/Users/jacopx/Development/labyrinth/labyrinth/__main__.py", line 35, in run
    win.addstr(1,0,str(solver.labyrinth))
_curses.error: addwstr() returned ERR
```

I run it on my macOS with:
```
$ python3 --version
Python 3.6.2
```

Could you help me?

**Comment by mooow** [comment]
We need more information about what's going on.

Checkout this branch which has support for logging:
```
git fetch
git checkout --track origin/debug
```

then post the output of `python3 -m labyrinth --log DEBUG`

It might be useful, also, to get the size of the terminal using terminfo. I don't know about bash, but if you use zsh you can do:
```
echoti lines
echoti cols
```

Thank you for the support.

**Comment by Jacopx** [comment]
This is the run:
```
$ python3 -m labyrinth --log DEBUG
DEBUG:root:LINES=30 COLS=134
DEBUG:root:CONF: {'rows': 28, 'cols': 66, 'delay': 0.005, 'prob': 0.15, 'log': 'DEBUG'}
```
And the dimension of my terminal are: `133:30`

**Comment by mooow** [comment]
As far as I can tell from this, the only "wrong" thing here is that the terminal size given by python's curses is 30x134 while terminfo says it's 30x133. Thus, curses tries to access a portion of screen which actually doesn't exist, failing.

I wasn't able to reproduce the error, so I'm closing until we have something more insightful.
Cheers.
